// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_raft_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_raft_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_raft_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_raft_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_raft_2eproto;
namespace raftpb {
class AppendEntriesRequest;
struct AppendEntriesRequestDefaultTypeInternal;
extern AppendEntriesRequestDefaultTypeInternal _AppendEntriesRequest_default_instance_;
class AppendEntriesResponse;
struct AppendEntriesResponseDefaultTypeInternal;
extern AppendEntriesResponseDefaultTypeInternal _AppendEntriesResponse_default_instance_;
class LogEntry;
struct LogEntryDefaultTypeInternal;
extern LogEntryDefaultTypeInternal _LogEntry_default_instance_;
class RequestVoteRequest;
struct RequestVoteRequestDefaultTypeInternal;
extern RequestVoteRequestDefaultTypeInternal _RequestVoteRequest_default_instance_;
class RequestVoteResponse;
struct RequestVoteResponseDefaultTypeInternal;
extern RequestVoteResponseDefaultTypeInternal _RequestVoteResponse_default_instance_;
}  // namespace raftpb
PROTOBUF_NAMESPACE_OPEN
template<> ::raftpb::AppendEntriesRequest* Arena::CreateMaybeMessage<::raftpb::AppendEntriesRequest>(Arena*);
template<> ::raftpb::AppendEntriesResponse* Arena::CreateMaybeMessage<::raftpb::AppendEntriesResponse>(Arena*);
template<> ::raftpb::LogEntry* Arena::CreateMaybeMessage<::raftpb::LogEntry>(Arena*);
template<> ::raftpb::RequestVoteRequest* Arena::CreateMaybeMessage<::raftpb::RequestVoteRequest>(Arena*);
template<> ::raftpb::RequestVoteResponse* Arena::CreateMaybeMessage<::raftpb::RequestVoteResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace raftpb {

enum LogEntry_EntryType : int {
  LogEntry_EntryType_ENTRY_NORMAL = 0,
  LogEntry_EntryType_ENTRY_CONF_CHANGE = 1,
  LogEntry_EntryType_LogEntry_EntryType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  LogEntry_EntryType_LogEntry_EntryType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool LogEntry_EntryType_IsValid(int value);
constexpr LogEntry_EntryType LogEntry_EntryType_EntryType_MIN = LogEntry_EntryType_ENTRY_NORMAL;
constexpr LogEntry_EntryType LogEntry_EntryType_EntryType_MAX = LogEntry_EntryType_ENTRY_CONF_CHANGE;
constexpr int LogEntry_EntryType_EntryType_ARRAYSIZE = LogEntry_EntryType_EntryType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LogEntry_EntryType_descriptor();
template<typename T>
inline const std::string& LogEntry_EntryType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LogEntry_EntryType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LogEntry_EntryType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LogEntry_EntryType_descriptor(), enum_t_value);
}
inline bool LogEntry_EntryType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LogEntry_EntryType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LogEntry_EntryType>(
    LogEntry_EntryType_descriptor(), name, value);
}
// ===================================================================

class LogEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raftpb.LogEntry) */ {
 public:
  inline LogEntry() : LogEntry(nullptr) {}
  ~LogEntry() override;
  explicit PROTOBUF_CONSTEXPR LogEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogEntry(const LogEntry& from);
  LogEntry(LogEntry&& from) noexcept
    : LogEntry() {
    *this = ::std::move(from);
  }

  inline LogEntry& operator=(const LogEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogEntry& operator=(LogEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogEntry* internal_default_instance() {
    return reinterpret_cast<const LogEntry*>(
               &_LogEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LogEntry& a, LogEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(LogEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LogEntry& from) {
    LogEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raftpb.LogEntry";
  }
  protected:
  explicit LogEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef LogEntry_EntryType EntryType;
  static constexpr EntryType ENTRY_NORMAL =
    LogEntry_EntryType_ENTRY_NORMAL;
  static constexpr EntryType ENTRY_CONF_CHANGE =
    LogEntry_EntryType_ENTRY_CONF_CHANGE;
  static inline bool EntryType_IsValid(int value) {
    return LogEntry_EntryType_IsValid(value);
  }
  static constexpr EntryType EntryType_MIN =
    LogEntry_EntryType_EntryType_MIN;
  static constexpr EntryType EntryType_MAX =
    LogEntry_EntryType_EntryType_MAX;
  static constexpr int EntryType_ARRAYSIZE =
    LogEntry_EntryType_EntryType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  EntryType_descriptor() {
    return LogEntry_EntryType_descriptor();
  }
  template<typename T>
  static inline const std::string& EntryType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, EntryType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function EntryType_Name.");
    return LogEntry_EntryType_Name(enum_t_value);
  }
  static inline bool EntryType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      EntryType* value) {
    return LogEntry_EntryType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 4,
    kTermFieldNumber = 1,
    kIndexFieldNumber = 2,
    kTypeFieldNumber = 3,
  };
  // bytes data = 4;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // uint64 term = 1;
  void clear_term();
  uint64_t term() const;
  void set_term(uint64_t value);
  private:
  uint64_t _internal_term() const;
  void _internal_set_term(uint64_t value);
  public:

  // uint64 index = 2;
  void clear_index();
  uint64_t index() const;
  void set_index(uint64_t value);
  private:
  uint64_t _internal_index() const;
  void _internal_set_index(uint64_t value);
  public:

  // .raftpb.LogEntry.EntryType type = 3;
  void clear_type();
  ::raftpb::LogEntry_EntryType type() const;
  void set_type(::raftpb::LogEntry_EntryType value);
  private:
  ::raftpb::LogEntry_EntryType _internal_type() const;
  void _internal_set_type(::raftpb::LogEntry_EntryType value);
  public:

  // @@protoc_insertion_point(class_scope:raftpb.LogEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    uint64_t term_;
    uint64_t index_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_2eproto;
};
// -------------------------------------------------------------------

class RequestVoteRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raftpb.RequestVoteRequest) */ {
 public:
  inline RequestVoteRequest() : RequestVoteRequest(nullptr) {}
  ~RequestVoteRequest() override;
  explicit PROTOBUF_CONSTEXPR RequestVoteRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RequestVoteRequest(const RequestVoteRequest& from);
  RequestVoteRequest(RequestVoteRequest&& from) noexcept
    : RequestVoteRequest() {
    *this = ::std::move(from);
  }

  inline RequestVoteRequest& operator=(const RequestVoteRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestVoteRequest& operator=(RequestVoteRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestVoteRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const RequestVoteRequest* internal_default_instance() {
    return reinterpret_cast<const RequestVoteRequest*>(
               &_RequestVoteRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RequestVoteRequest& a, RequestVoteRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(RequestVoteRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestVoteRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestVoteRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RequestVoteRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RequestVoteRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RequestVoteRequest& from) {
    RequestVoteRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestVoteRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raftpb.RequestVoteRequest";
  }
  protected:
  explicit RequestVoteRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kLastLogIndexFieldNumber = 3,
    kLastLogTermFieldNumber = 4,
    kCandidateIdFieldNumber = 2,
  };
  // uint64 term = 1;
  void clear_term();
  uint64_t term() const;
  void set_term(uint64_t value);
  private:
  uint64_t _internal_term() const;
  void _internal_set_term(uint64_t value);
  public:

  // uint64 last_log_index = 3;
  void clear_last_log_index();
  uint64_t last_log_index() const;
  void set_last_log_index(uint64_t value);
  private:
  uint64_t _internal_last_log_index() const;
  void _internal_set_last_log_index(uint64_t value);
  public:

  // uint64 last_log_term = 4;
  void clear_last_log_term();
  uint64_t last_log_term() const;
  void set_last_log_term(uint64_t value);
  private:
  uint64_t _internal_last_log_term() const;
  void _internal_set_last_log_term(uint64_t value);
  public:

  // uint32 candidate_id = 2;
  void clear_candidate_id();
  uint32_t candidate_id() const;
  void set_candidate_id(uint32_t value);
  private:
  uint32_t _internal_candidate_id() const;
  void _internal_set_candidate_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raftpb.RequestVoteRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t term_;
    uint64_t last_log_index_;
    uint64_t last_log_term_;
    uint32_t candidate_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_2eproto;
};
// -------------------------------------------------------------------

class RequestVoteResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raftpb.RequestVoteResponse) */ {
 public:
  inline RequestVoteResponse() : RequestVoteResponse(nullptr) {}
  ~RequestVoteResponse() override;
  explicit PROTOBUF_CONSTEXPR RequestVoteResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RequestVoteResponse(const RequestVoteResponse& from);
  RequestVoteResponse(RequestVoteResponse&& from) noexcept
    : RequestVoteResponse() {
    *this = ::std::move(from);
  }

  inline RequestVoteResponse& operator=(const RequestVoteResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestVoteResponse& operator=(RequestVoteResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestVoteResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const RequestVoteResponse* internal_default_instance() {
    return reinterpret_cast<const RequestVoteResponse*>(
               &_RequestVoteResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RequestVoteResponse& a, RequestVoteResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(RequestVoteResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestVoteResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestVoteResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RequestVoteResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RequestVoteResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RequestVoteResponse& from) {
    RequestVoteResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestVoteResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raftpb.RequestVoteResponse";
  }
  protected:
  explicit RequestVoteResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kVoteGrantedFieldNumber = 2,
  };
  // uint64 term = 1;
  void clear_term();
  uint64_t term() const;
  void set_term(uint64_t value);
  private:
  uint64_t _internal_term() const;
  void _internal_set_term(uint64_t value);
  public:

  // bool vote_granted = 2;
  void clear_vote_granted();
  bool vote_granted() const;
  void set_vote_granted(bool value);
  private:
  bool _internal_vote_granted() const;
  void _internal_set_vote_granted(bool value);
  public:

  // @@protoc_insertion_point(class_scope:raftpb.RequestVoteResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t term_;
    bool vote_granted_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_2eproto;
};
// -------------------------------------------------------------------

class AppendEntriesRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raftpb.AppendEntriesRequest) */ {
 public:
  inline AppendEntriesRequest() : AppendEntriesRequest(nullptr) {}
  ~AppendEntriesRequest() override;
  explicit PROTOBUF_CONSTEXPR AppendEntriesRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppendEntriesRequest(const AppendEntriesRequest& from);
  AppendEntriesRequest(AppendEntriesRequest&& from) noexcept
    : AppendEntriesRequest() {
    *this = ::std::move(from);
  }

  inline AppendEntriesRequest& operator=(const AppendEntriesRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppendEntriesRequest& operator=(AppendEntriesRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AppendEntriesRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppendEntriesRequest* internal_default_instance() {
    return reinterpret_cast<const AppendEntriesRequest*>(
               &_AppendEntriesRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(AppendEntriesRequest& a, AppendEntriesRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AppendEntriesRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppendEntriesRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AppendEntriesRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AppendEntriesRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AppendEntriesRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AppendEntriesRequest& from) {
    AppendEntriesRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppendEntriesRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raftpb.AppendEntriesRequest";
  }
  protected:
  explicit AppendEntriesRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntriesFieldNumber = 5,
    kTermFieldNumber = 1,
    kPrevLogIndexFieldNumber = 3,
    kPrevLogTermFieldNumber = 4,
    kLeaderCommitFieldNumber = 6,
    kLeaderIdFieldNumber = 2,
  };
  // repeated .raftpb.LogEntry entries = 5;
  int entries_size() const;
  private:
  int _internal_entries_size() const;
  public:
  void clear_entries();
  ::raftpb::LogEntry* mutable_entries(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftpb::LogEntry >*
      mutable_entries();
  private:
  const ::raftpb::LogEntry& _internal_entries(int index) const;
  ::raftpb::LogEntry* _internal_add_entries();
  public:
  const ::raftpb::LogEntry& entries(int index) const;
  ::raftpb::LogEntry* add_entries();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftpb::LogEntry >&
      entries() const;

  // uint64 term = 1;
  void clear_term();
  uint64_t term() const;
  void set_term(uint64_t value);
  private:
  uint64_t _internal_term() const;
  void _internal_set_term(uint64_t value);
  public:

  // uint64 prev_log_index = 3;
  void clear_prev_log_index();
  uint64_t prev_log_index() const;
  void set_prev_log_index(uint64_t value);
  private:
  uint64_t _internal_prev_log_index() const;
  void _internal_set_prev_log_index(uint64_t value);
  public:

  // uint64 prev_log_term = 4;
  void clear_prev_log_term();
  uint64_t prev_log_term() const;
  void set_prev_log_term(uint64_t value);
  private:
  uint64_t _internal_prev_log_term() const;
  void _internal_set_prev_log_term(uint64_t value);
  public:

  // uint64 leader_commit = 6;
  void clear_leader_commit();
  uint64_t leader_commit() const;
  void set_leader_commit(uint64_t value);
  private:
  uint64_t _internal_leader_commit() const;
  void _internal_set_leader_commit(uint64_t value);
  public:

  // uint32 leader_id = 2;
  void clear_leader_id();
  uint32_t leader_id() const;
  void set_leader_id(uint32_t value);
  private:
  uint32_t _internal_leader_id() const;
  void _internal_set_leader_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:raftpb.AppendEntriesRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftpb::LogEntry > entries_;
    uint64_t term_;
    uint64_t prev_log_index_;
    uint64_t prev_log_term_;
    uint64_t leader_commit_;
    uint32_t leader_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_2eproto;
};
// -------------------------------------------------------------------

class AppendEntriesResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:raftpb.AppendEntriesResponse) */ {
 public:
  inline AppendEntriesResponse() : AppendEntriesResponse(nullptr) {}
  ~AppendEntriesResponse() override;
  explicit PROTOBUF_CONSTEXPR AppendEntriesResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppendEntriesResponse(const AppendEntriesResponse& from);
  AppendEntriesResponse(AppendEntriesResponse&& from) noexcept
    : AppendEntriesResponse() {
    *this = ::std::move(from);
  }

  inline AppendEntriesResponse& operator=(const AppendEntriesResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppendEntriesResponse& operator=(AppendEntriesResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AppendEntriesResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppendEntriesResponse* internal_default_instance() {
    return reinterpret_cast<const AppendEntriesResponse*>(
               &_AppendEntriesResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(AppendEntriesResponse& a, AppendEntriesResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(AppendEntriesResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppendEntriesResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AppendEntriesResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AppendEntriesResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AppendEntriesResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AppendEntriesResponse& from) {
    AppendEntriesResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppendEntriesResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "raftpb.AppendEntriesResponse";
  }
  protected:
  explicit AppendEntriesResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kConflictIndexFieldNumber = 3,
    kConflictTermFieldNumber = 4,
    kSuccessFieldNumber = 2,
  };
  // uint64 term = 1;
  void clear_term();
  uint64_t term() const;
  void set_term(uint64_t value);
  private:
  uint64_t _internal_term() const;
  void _internal_set_term(uint64_t value);
  public:

  // uint64 conflict_index = 3;
  void clear_conflict_index();
  uint64_t conflict_index() const;
  void set_conflict_index(uint64_t value);
  private:
  uint64_t _internal_conflict_index() const;
  void _internal_set_conflict_index(uint64_t value);
  public:

  // uint64 conflict_term = 4;
  void clear_conflict_term();
  uint64_t conflict_term() const;
  void set_conflict_term(uint64_t value);
  private:
  uint64_t _internal_conflict_term() const;
  void _internal_set_conflict_term(uint64_t value);
  public:

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:raftpb.AppendEntriesResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t term_;
    uint64_t conflict_index_;
    uint64_t conflict_term_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_raft_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LogEntry

// uint64 term = 1;
inline void LogEntry::clear_term() {
  _impl_.term_ = uint64_t{0u};
}
inline uint64_t LogEntry::_internal_term() const {
  return _impl_.term_;
}
inline uint64_t LogEntry::term() const {
  // @@protoc_insertion_point(field_get:raftpb.LogEntry.term)
  return _internal_term();
}
inline void LogEntry::_internal_set_term(uint64_t value) {
  
  _impl_.term_ = value;
}
inline void LogEntry::set_term(uint64_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raftpb.LogEntry.term)
}

// uint64 index = 2;
inline void LogEntry::clear_index() {
  _impl_.index_ = uint64_t{0u};
}
inline uint64_t LogEntry::_internal_index() const {
  return _impl_.index_;
}
inline uint64_t LogEntry::index() const {
  // @@protoc_insertion_point(field_get:raftpb.LogEntry.index)
  return _internal_index();
}
inline void LogEntry::_internal_set_index(uint64_t value) {
  
  _impl_.index_ = value;
}
inline void LogEntry::set_index(uint64_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:raftpb.LogEntry.index)
}

// .raftpb.LogEntry.EntryType type = 3;
inline void LogEntry::clear_type() {
  _impl_.type_ = 0;
}
inline ::raftpb::LogEntry_EntryType LogEntry::_internal_type() const {
  return static_cast< ::raftpb::LogEntry_EntryType >(_impl_.type_);
}
inline ::raftpb::LogEntry_EntryType LogEntry::type() const {
  // @@protoc_insertion_point(field_get:raftpb.LogEntry.type)
  return _internal_type();
}
inline void LogEntry::_internal_set_type(::raftpb::LogEntry_EntryType value) {
  
  _impl_.type_ = value;
}
inline void LogEntry::set_type(::raftpb::LogEntry_EntryType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:raftpb.LogEntry.type)
}

// bytes data = 4;
inline void LogEntry::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& LogEntry::data() const {
  // @@protoc_insertion_point(field_get:raftpb.LogEntry.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogEntry::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:raftpb.LogEntry.data)
}
inline std::string* LogEntry::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:raftpb.LogEntry.data)
  return _s;
}
inline const std::string& LogEntry::_internal_data() const {
  return _impl_.data_.Get();
}
inline void LogEntry::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* LogEntry::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* LogEntry::release_data() {
  // @@protoc_insertion_point(field_release:raftpb.LogEntry.data)
  return _impl_.data_.Release();
}
inline void LogEntry::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:raftpb.LogEntry.data)
}

// -------------------------------------------------------------------

// RequestVoteRequest

// uint64 term = 1;
inline void RequestVoteRequest::clear_term() {
  _impl_.term_ = uint64_t{0u};
}
inline uint64_t RequestVoteRequest::_internal_term() const {
  return _impl_.term_;
}
inline uint64_t RequestVoteRequest::term() const {
  // @@protoc_insertion_point(field_get:raftpb.RequestVoteRequest.term)
  return _internal_term();
}
inline void RequestVoteRequest::_internal_set_term(uint64_t value) {
  
  _impl_.term_ = value;
}
inline void RequestVoteRequest::set_term(uint64_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raftpb.RequestVoteRequest.term)
}

// uint32 candidate_id = 2;
inline void RequestVoteRequest::clear_candidate_id() {
  _impl_.candidate_id_ = 0u;
}
inline uint32_t RequestVoteRequest::_internal_candidate_id() const {
  return _impl_.candidate_id_;
}
inline uint32_t RequestVoteRequest::candidate_id() const {
  // @@protoc_insertion_point(field_get:raftpb.RequestVoteRequest.candidate_id)
  return _internal_candidate_id();
}
inline void RequestVoteRequest::_internal_set_candidate_id(uint32_t value) {
  
  _impl_.candidate_id_ = value;
}
inline void RequestVoteRequest::set_candidate_id(uint32_t value) {
  _internal_set_candidate_id(value);
  // @@protoc_insertion_point(field_set:raftpb.RequestVoteRequest.candidate_id)
}

// uint64 last_log_index = 3;
inline void RequestVoteRequest::clear_last_log_index() {
  _impl_.last_log_index_ = uint64_t{0u};
}
inline uint64_t RequestVoteRequest::_internal_last_log_index() const {
  return _impl_.last_log_index_;
}
inline uint64_t RequestVoteRequest::last_log_index() const {
  // @@protoc_insertion_point(field_get:raftpb.RequestVoteRequest.last_log_index)
  return _internal_last_log_index();
}
inline void RequestVoteRequest::_internal_set_last_log_index(uint64_t value) {
  
  _impl_.last_log_index_ = value;
}
inline void RequestVoteRequest::set_last_log_index(uint64_t value) {
  _internal_set_last_log_index(value);
  // @@protoc_insertion_point(field_set:raftpb.RequestVoteRequest.last_log_index)
}

// uint64 last_log_term = 4;
inline void RequestVoteRequest::clear_last_log_term() {
  _impl_.last_log_term_ = uint64_t{0u};
}
inline uint64_t RequestVoteRequest::_internal_last_log_term() const {
  return _impl_.last_log_term_;
}
inline uint64_t RequestVoteRequest::last_log_term() const {
  // @@protoc_insertion_point(field_get:raftpb.RequestVoteRequest.last_log_term)
  return _internal_last_log_term();
}
inline void RequestVoteRequest::_internal_set_last_log_term(uint64_t value) {
  
  _impl_.last_log_term_ = value;
}
inline void RequestVoteRequest::set_last_log_term(uint64_t value) {
  _internal_set_last_log_term(value);
  // @@protoc_insertion_point(field_set:raftpb.RequestVoteRequest.last_log_term)
}

// -------------------------------------------------------------------

// RequestVoteResponse

// uint64 term = 1;
inline void RequestVoteResponse::clear_term() {
  _impl_.term_ = uint64_t{0u};
}
inline uint64_t RequestVoteResponse::_internal_term() const {
  return _impl_.term_;
}
inline uint64_t RequestVoteResponse::term() const {
  // @@protoc_insertion_point(field_get:raftpb.RequestVoteResponse.term)
  return _internal_term();
}
inline void RequestVoteResponse::_internal_set_term(uint64_t value) {
  
  _impl_.term_ = value;
}
inline void RequestVoteResponse::set_term(uint64_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raftpb.RequestVoteResponse.term)
}

// bool vote_granted = 2;
inline void RequestVoteResponse::clear_vote_granted() {
  _impl_.vote_granted_ = false;
}
inline bool RequestVoteResponse::_internal_vote_granted() const {
  return _impl_.vote_granted_;
}
inline bool RequestVoteResponse::vote_granted() const {
  // @@protoc_insertion_point(field_get:raftpb.RequestVoteResponse.vote_granted)
  return _internal_vote_granted();
}
inline void RequestVoteResponse::_internal_set_vote_granted(bool value) {
  
  _impl_.vote_granted_ = value;
}
inline void RequestVoteResponse::set_vote_granted(bool value) {
  _internal_set_vote_granted(value);
  // @@protoc_insertion_point(field_set:raftpb.RequestVoteResponse.vote_granted)
}

// -------------------------------------------------------------------

// AppendEntriesRequest

// uint64 term = 1;
inline void AppendEntriesRequest::clear_term() {
  _impl_.term_ = uint64_t{0u};
}
inline uint64_t AppendEntriesRequest::_internal_term() const {
  return _impl_.term_;
}
inline uint64_t AppendEntriesRequest::term() const {
  // @@protoc_insertion_point(field_get:raftpb.AppendEntriesRequest.term)
  return _internal_term();
}
inline void AppendEntriesRequest::_internal_set_term(uint64_t value) {
  
  _impl_.term_ = value;
}
inline void AppendEntriesRequest::set_term(uint64_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raftpb.AppendEntriesRequest.term)
}

// uint32 leader_id = 2;
inline void AppendEntriesRequest::clear_leader_id() {
  _impl_.leader_id_ = 0u;
}
inline uint32_t AppendEntriesRequest::_internal_leader_id() const {
  return _impl_.leader_id_;
}
inline uint32_t AppendEntriesRequest::leader_id() const {
  // @@protoc_insertion_point(field_get:raftpb.AppendEntriesRequest.leader_id)
  return _internal_leader_id();
}
inline void AppendEntriesRequest::_internal_set_leader_id(uint32_t value) {
  
  _impl_.leader_id_ = value;
}
inline void AppendEntriesRequest::set_leader_id(uint32_t value) {
  _internal_set_leader_id(value);
  // @@protoc_insertion_point(field_set:raftpb.AppendEntriesRequest.leader_id)
}

// uint64 prev_log_index = 3;
inline void AppendEntriesRequest::clear_prev_log_index() {
  _impl_.prev_log_index_ = uint64_t{0u};
}
inline uint64_t AppendEntriesRequest::_internal_prev_log_index() const {
  return _impl_.prev_log_index_;
}
inline uint64_t AppendEntriesRequest::prev_log_index() const {
  // @@protoc_insertion_point(field_get:raftpb.AppendEntriesRequest.prev_log_index)
  return _internal_prev_log_index();
}
inline void AppendEntriesRequest::_internal_set_prev_log_index(uint64_t value) {
  
  _impl_.prev_log_index_ = value;
}
inline void AppendEntriesRequest::set_prev_log_index(uint64_t value) {
  _internal_set_prev_log_index(value);
  // @@protoc_insertion_point(field_set:raftpb.AppendEntriesRequest.prev_log_index)
}

// uint64 prev_log_term = 4;
inline void AppendEntriesRequest::clear_prev_log_term() {
  _impl_.prev_log_term_ = uint64_t{0u};
}
inline uint64_t AppendEntriesRequest::_internal_prev_log_term() const {
  return _impl_.prev_log_term_;
}
inline uint64_t AppendEntriesRequest::prev_log_term() const {
  // @@protoc_insertion_point(field_get:raftpb.AppendEntriesRequest.prev_log_term)
  return _internal_prev_log_term();
}
inline void AppendEntriesRequest::_internal_set_prev_log_term(uint64_t value) {
  
  _impl_.prev_log_term_ = value;
}
inline void AppendEntriesRequest::set_prev_log_term(uint64_t value) {
  _internal_set_prev_log_term(value);
  // @@protoc_insertion_point(field_set:raftpb.AppendEntriesRequest.prev_log_term)
}

// repeated .raftpb.LogEntry entries = 5;
inline int AppendEntriesRequest::_internal_entries_size() const {
  return _impl_.entries_.size();
}
inline int AppendEntriesRequest::entries_size() const {
  return _internal_entries_size();
}
inline void AppendEntriesRequest::clear_entries() {
  _impl_.entries_.Clear();
}
inline ::raftpb::LogEntry* AppendEntriesRequest::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:raftpb.AppendEntriesRequest.entries)
  return _impl_.entries_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftpb::LogEntry >*
AppendEntriesRequest::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:raftpb.AppendEntriesRequest.entries)
  return &_impl_.entries_;
}
inline const ::raftpb::LogEntry& AppendEntriesRequest::_internal_entries(int index) const {
  return _impl_.entries_.Get(index);
}
inline const ::raftpb::LogEntry& AppendEntriesRequest::entries(int index) const {
  // @@protoc_insertion_point(field_get:raftpb.AppendEntriesRequest.entries)
  return _internal_entries(index);
}
inline ::raftpb::LogEntry* AppendEntriesRequest::_internal_add_entries() {
  return _impl_.entries_.Add();
}
inline ::raftpb::LogEntry* AppendEntriesRequest::add_entries() {
  ::raftpb::LogEntry* _add = _internal_add_entries();
  // @@protoc_insertion_point(field_add:raftpb.AppendEntriesRequest.entries)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::raftpb::LogEntry >&
AppendEntriesRequest::entries() const {
  // @@protoc_insertion_point(field_list:raftpb.AppendEntriesRequest.entries)
  return _impl_.entries_;
}

// uint64 leader_commit = 6;
inline void AppendEntriesRequest::clear_leader_commit() {
  _impl_.leader_commit_ = uint64_t{0u};
}
inline uint64_t AppendEntriesRequest::_internal_leader_commit() const {
  return _impl_.leader_commit_;
}
inline uint64_t AppendEntriesRequest::leader_commit() const {
  // @@protoc_insertion_point(field_get:raftpb.AppendEntriesRequest.leader_commit)
  return _internal_leader_commit();
}
inline void AppendEntriesRequest::_internal_set_leader_commit(uint64_t value) {
  
  _impl_.leader_commit_ = value;
}
inline void AppendEntriesRequest::set_leader_commit(uint64_t value) {
  _internal_set_leader_commit(value);
  // @@protoc_insertion_point(field_set:raftpb.AppendEntriesRequest.leader_commit)
}

// -------------------------------------------------------------------

// AppendEntriesResponse

// uint64 term = 1;
inline void AppendEntriesResponse::clear_term() {
  _impl_.term_ = uint64_t{0u};
}
inline uint64_t AppendEntriesResponse::_internal_term() const {
  return _impl_.term_;
}
inline uint64_t AppendEntriesResponse::term() const {
  // @@protoc_insertion_point(field_get:raftpb.AppendEntriesResponse.term)
  return _internal_term();
}
inline void AppendEntriesResponse::_internal_set_term(uint64_t value) {
  
  _impl_.term_ = value;
}
inline void AppendEntriesResponse::set_term(uint64_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:raftpb.AppendEntriesResponse.term)
}

// bool success = 2;
inline void AppendEntriesResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool AppendEntriesResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool AppendEntriesResponse::success() const {
  // @@protoc_insertion_point(field_get:raftpb.AppendEntriesResponse.success)
  return _internal_success();
}
inline void AppendEntriesResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void AppendEntriesResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:raftpb.AppendEntriesResponse.success)
}

// uint64 conflict_index = 3;
inline void AppendEntriesResponse::clear_conflict_index() {
  _impl_.conflict_index_ = uint64_t{0u};
}
inline uint64_t AppendEntriesResponse::_internal_conflict_index() const {
  return _impl_.conflict_index_;
}
inline uint64_t AppendEntriesResponse::conflict_index() const {
  // @@protoc_insertion_point(field_get:raftpb.AppendEntriesResponse.conflict_index)
  return _internal_conflict_index();
}
inline void AppendEntriesResponse::_internal_set_conflict_index(uint64_t value) {
  
  _impl_.conflict_index_ = value;
}
inline void AppendEntriesResponse::set_conflict_index(uint64_t value) {
  _internal_set_conflict_index(value);
  // @@protoc_insertion_point(field_set:raftpb.AppendEntriesResponse.conflict_index)
}

// uint64 conflict_term = 4;
inline void AppendEntriesResponse::clear_conflict_term() {
  _impl_.conflict_term_ = uint64_t{0u};
}
inline uint64_t AppendEntriesResponse::_internal_conflict_term() const {
  return _impl_.conflict_term_;
}
inline uint64_t AppendEntriesResponse::conflict_term() const {
  // @@protoc_insertion_point(field_get:raftpb.AppendEntriesResponse.conflict_term)
  return _internal_conflict_term();
}
inline void AppendEntriesResponse::_internal_set_conflict_term(uint64_t value) {
  
  _impl_.conflict_term_ = value;
}
inline void AppendEntriesResponse::set_conflict_term(uint64_t value) {
  _internal_set_conflict_term(value);
  // @@protoc_insertion_point(field_set:raftpb.AppendEntriesResponse.conflict_term)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace raftpb

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::raftpb::LogEntry_EntryType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::raftpb::LogEntry_EntryType>() {
  return ::raftpb::LogEntry_EntryType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_raft_2eproto
