#pragma once

#include <grpcpp/grpcpp.h>
#include "raft.grpc.pb.h"
#include "raft/raft_node.h"
#include "common/logger.h"

namespace raftkv {

// This class inherits from the code generated by protoc.
// It acts as the "Receptionist" for incoming RPCs.
class RaftRpcServiceImpl final : public raftpb::RaftService::Service {
public:
    // We inject the RaftNode so we can forward requests to it
    explicit RaftRpcServiceImpl(RaftNode& node) : node_(node) {}

    // 1. Handle RequestVote RPC
    grpc::Status RequestVote(grpc::ServerContext* context, 
                             const raftpb::RequestVoteRequest* request, 
                             raftpb::RequestVoteResponse* response) override {
        // Log that we received a request
        // LOG_DEBUG("RPC Received: RequestVote from Node " << request->candidate_id());

        // Forward logic to the Brain (RaftNode)
        node_.HandleRequestVote(*request, response);
        
        return grpc::Status::OK;
    }

    // 2. Handle AppendEntries RPC (Heartbeat)
    grpc::Status AppendEntries(grpc::ServerContext* context, 
                               const raftpb::AppendEntriesRequest* request, 
                               raftpb::AppendEntriesResponse* response) override {
        // LOG_DEBUG("RPC Received: AppendEntries from Node " << request->leader_id());
        
        // Forward logic to the Brain (RaftNode)
        node_.HandleAppendEntries(*request, response);

        return grpc::Status::OK;
    }

private:
    RaftNode& node_;
};

} // namespace raftkv